# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'usedcars.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UsedCars(object):
    def setupUi(self, UsedCars):
        UsedCars.setObjectName("UsedCars")
        UsedCars.resize(400, 300)
        self.label = QtWidgets.QLabel(UsedCars)
        self.label.setGeometry(QtCore.QRect(120, 90, 181, 61))
        self.label.setObjectName("label")

        self.retranslateUi(UsedCars)
        QtCore.QMetaObject.connectSlotsByName(UsedCars)

    def retranslateUi(self, UsedCars):
        _translate = QtCore.QCoreApplication.translate
        UsedCars.setWindowTitle(_translate("UsedCars", "Dialog"))
        self.label.setText(_translate("UsedCars", "Used Car"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UsedCars = QtWidgets.QDialog()
    ui = Ui_UsedCars()
    ui.setupUi(UsedCars)
    UsedCars.show()
    sys.exit(app.exec_())
